services:
  mongodb:
    image: mongo:7
    container_name: quotematic-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - quotematic_mongodb_data:/data/db

volumes:
  quotematic_mongodb_data: