"$schema" = "https://starship.rs/config-schema.json"

add_newline = false
command_timeout = 800
format = """
$directory$git_branch$git_status$fill$nodejs$python$golang$rust$java$docker_context
$status$character
"""
right_format = "$cmd_duration"

[directory]
style = "bold cyan"
truncate_to_repo = false
truncation_length = 3
read_only = " 󰌾"
read_only_style = "bold red"

[git_branch]
symbol = " "
style = "bold purple"
format = " [$symbol$branch]($style)"

[git_status]
style = "bold red"
format = "([$all_status$ahead_behind]($style))"

[fill]
symbol = " "

[nodejs]
symbol = "󰎙 "
style = "bold green"
format = "[$symbol$version]($style) "

[python]
symbol = " "
style = "bold yellow"
format = "[$symbol$version]($style) "

[golang]
symbol = " "
style = "bold cyan"
format = "[$symbol$version]($style) "

[rust]
symbol = "󱘗 "
style = "bold red"
format = "[$symbol$version]($style) "

[java]
symbol = " "
style = "bold blue"
format = "[$symbol$version]($style) "

[docker_context]
symbol = " "
style = "bold blue"
format = "[$symbol$context]($style) "

[cmd_duration]
min_time = 500
format = "[$duration](dimmed yellow)"

[status]
disabled = false
format = "[$symbol$status ]($style)"
map_symbol = true
symbol = "✘ "
style = "bold red"

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bold yellow)"
